// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3BXiHVE8k-FToVTgqF591CjYwjsq3Ofw',
    appId: '1:221598186365:web:eb60477f704f1c95356a14',
    messagingSenderId: '221598186365',
    projectId: 'qreversi',
    authDomain: 'qreversi.firebaseapp.com',
    storageBucket: 'qreversi.firebasestorage.app',
    measurementId: 'G-ENCX7WPMY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP_jxXBOTKu9YyyPL1pA2Aw0opeJLGa2k',
    appId: '1:221598186365:android:8c8a34487ea532f2356a14',
    messagingSenderId: '221598186365',
    projectId: 'qreversi',
    storageBucket: 'qreversi.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZivou0Thq6weHsN6M0ldbPJBmfMZxXxQ',
    appId: '1:221598186365:ios:cbdf95f540abe565356a14',
    messagingSenderId: '221598186365',
    projectId: 'qreversi',
    storageBucket: 'qreversi.firebasestorage.app',
    iosBundleId: 'com.qReversi.app',
  );
}
