/**
 * Build curated NG-word lists for player display names.
 *
 * Sources:
 * - MosasoM/inappropriate-words-ja (MIT) — Sexual.txt, Offensive.txt
 * - shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words — ja, en
 * - App reserved names
 */
const fs = require("fs");
const path = require("path");

const root = __dirname;

function readLines(file) {
  return fs
    .readFileSync(path.join(root, file), "utf8")
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#"));
}

function normalize(raw) {
  return raw
    .normalize("NFKC")
    .toLowerCase()
    .replace(/[\s\u3000_\-・･./\\|'"`~!@#$%^&*()+=\[\]{};:,<>?？！。、「」『』（）]/g, "");
}

const FALSE_POSITIVES = new Set(
  [
    "イク",
    "嫌い",
    "女の子",
    "支配",
    "ファンタジー",
    "ラバー",
    "セクシーな",
    "ぽっちゃり",
    "いたずら",
    "フック",
    "なめ",
    "トップレス",
    "糖質",
    "sexy",
    "sexual",
    "sexually",
    "sexuality",
    "erotic",
    "erotism",
    "suck",
    "sucks",
    "xx",
    "xxx",
    "ass",
    "butt",
    "boob",
    "boobs",
    "tit",
    "tits",
    "gay",
    "nude",
    "nudity",
    "playboy",
    "escort",
    "horny",
    "kinky",
    "bondage",
    "humping",
    "intercourse",
    "genitals",
    "semen",
    "vulva",
    "anus",
    "rectum",
    "panties",
    "panty",
    "lingerie",
    "strip club",
    "taste my",
    "tied up",
    "undressing",
    "make me come",
    "girl on",
    "girl on top",
    "girls gone wild",
    "hot chick",
    "hot carl",
    "goodpoop",
    "goo girl",
    "babeland",
  ].map(normalize),
);

const RESERVED = [
  "admin",
  "administrator",
  "root",
  "system",
  "official",
  "support",
  "moderator",
  "staff",
  "owner",
  "null",
  "undefined",
  "qreversi",
  "q-reversi",
  "運営",
  "公式",
  "管理者",
  "運営者",
  "サポート",
  "事務局",
];

const sexual = readLines("_sexual.txt");
const offensive = readLines("_offensive.txt");
const ssJa = readLines("_ss_ja.txt");
const ssEn = readLines("_ss_en.txt");

const merged = new Map();

function add(raw, minLen) {
  const trimmed = raw.trim();
  if (!trimmed) return;
  const n = normalize(trimmed);
  if (!n || n.length < minLen) return;
  if (FALSE_POSITIVES.has(n)) return;
  const prev = merged.get(n);
  if (!prev || trimmed.length > prev.length) {
    merged.set(n, trimmed);
  }
}

for (const w of sexual) add(w, 2);
for (const w of offensive) add(w, 2);
for (const w of ssJa) add(w, 2);
for (const w of ssEn) add(w, 4);
for (const w of RESERVED) add(w, 2);

const words = [...merged.values()].sort((a, b) => a.localeCompare(b, "ja"));

const tsPath = path.join(root, "..", "src", "time_attack", "ngWords.ts");
const dartPath = path.join(
  root,
  "..",
  "..",
  "lib",
  "domain",
  "time_attack",
  "ng_word_list.dart",
);

const tsOut = `// GENERATED by functions/scripts/generate_ng_words.js — do not edit by hand.
// Sources:
// - https://github.com/MosasoM/inappropriate-words-ja (MIT)
// - https://github.com/shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
// - App reserved names (admin / 運営 / ...)

export const NG_WORDS: readonly string[] = ${JSON.stringify(words, null, 2)};

export function normalizeForNgCheck(raw: string): string {
  return raw
    .normalize("NFKC")
    .toLowerCase()
    .replace(/[\\s\\u3000_\\-・･./\\\\|'\`~!@#$%^&*()+=\\[\\]{};:,<>?？！。、「」『』（）]/g, "");
}

const NORMALIZED_NG_WORDS = new Set(
  NG_WORDS.map(normalizeForNgCheck).filter((w) => w.length >= 2),
);

/** true if the whole (normalized) name equals a blocked term */
export function containsNgWord(raw: string): boolean {
  const normalized = normalizeForNgCheck(raw);
  if (!normalized) return false;
  return NORMALIZED_NG_WORDS.has(normalized);
}
`;

function dartEscape(s) {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

const dartList = words.map((w) => `  '${dartEscape(w)}',`).join("\n");

const dartOut = `// GENERATED by functions/scripts/generate_ng_words.js — do not edit by hand.
// Sources:
// - https://github.com/MosasoM/inappropriate-words-ja (MIT)
// - https://github.com/shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
// - App reserved names (admin / 運営 / ...)

/// Client-side NG-word check. Server \`setPlayerName\` remains authoritative.
class NgWordList {
  NgWordList._();

  static const List<String> words = <String>[
${dartList}
  ];

  static final Set<String> _normalized = words
      .map(normalize)
      .where((w) => w.length >= 2)
      .toSet();

  /// Approximate NFKC for Latin full-width + strip separators + lower-case.
  static String normalize(String raw) {
    final buf = StringBuffer();
    for (final rune in raw.trim().runes) {
      var code = rune;
      if (code >= 0xFF21 && code <= 0xFF3A) {
        code = code - 0xFEE0;
      } else if (code >= 0xFF41 && code <= 0xFF5A) {
        code = code - 0xFEE0;
      } else if (code >= 0xFF10 && code <= 0xFF19) {
        code = code - 0xFEE0;
      }
      if (_isSeparator(code)) continue;
      buf.writeCharCode(code);
    }
    return buf.toString().toLowerCase();
  }

  static bool _isSeparator(int code) {
    if (code <= 0x20 || code == 0x7F || code == 0x3000) return true;
    switch (code) {
      case 0x5F: // _
      case 0x2D: // -
      case 0x30FB: // ・
      case 0xFF65: // ･
      case 0x2E: // .
      case 0x2F: // /
      case 0x5C: // \\
      case 0x7C: // |
      case 0x27: // '
      case 0x60: // \`
      case 0x22: // "
      case 0x7E: // ~
      case 0x21: // !
      case 0x40: // @
      case 0x23: // #
      case 0x24: // \$
      case 0x25: // %
      case 0x5E: // ^
      case 0x26: // &
      case 0x2A: // *
      case 0x28: // (
      case 0x29: // )
      case 0x2B: // +
      case 0x3D: // =
      case 0x5B: // [
      case 0x5D: // ]
      case 0x7B: // {
      case 0x7D: // }
      case 0x3B: // ;
      case 0x3A: // :
      case 0x2C: // ,
      case 0x3C: // <
      case 0x3E: // >
      case 0x3F: // ?
      case 0xFF1F: // ？
      case 0xFF01: // ！
      case 0x3002: // 。
      case 0x3001: // 、
      case 0x300C: // 「
      case 0x300D: // 」
      case 0x300E: // 『
      case 0x300F: // 』
      case 0xFF08: // （
      case 0xFF09: // ）
        return true;
      default:
        return false;
    }
  }

  /// 正規化後の名前全体が NG ワードと一致したときだけ true
  static bool containsNgWord(String raw) {
    final normalized = normalize(raw);
    if (normalized.isEmpty) return false;
    return _normalized.contains(normalized);
  }
}
`;

fs.writeFileSync(tsPath, tsOut, "utf8");
fs.writeFileSync(dartPath, dartOut, "utf8");
console.log(`Wrote ${words.length} words`);
console.log(tsPath);
console.log(dartPath);
